//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int InspectionId { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public int UserId { get; set; }
        public int AffectedPartId { get; set; }
        public int ShiftId { get; set; }
        public int AreaId { get; set; }
        public int Quantity { get; set; }
        public string Comment { get; set; }
        public string SerialNumber { get; set; }
        public int AssemblyLineId { get; set; }
        public int DefectId { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual AffectedPart AffectedPart { get; set; }
        public virtual Area Area { get; set; }
        public virtual AssemblyLine AssemblyLine { get; set; }
        public virtual Defect Defect { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Users User { get; set; }
    }
}
