//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionSearch
    {
        public int InspectionId { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public int UserId { get; set; }
        public int ShiftId { get; set; }
        public string ShiftName { get; set; }
        public string AssemblyLineName { get; set; }
        public int AssemblyLineId { get; set; }
        public string AreaName { get; set; }
        public int AreaId { get; set; }
        public string DefectName { get; set; }
        public int DefectId { get; set; }
        public string AffectedPartName { get; set; }
        public int AffectedPartId { get; set; }
        public string Comment { get; set; }
        public string SerialNumber { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string UserName { get; set; }
    }
}
